#!/usr/bin/env python3
"""Builds supabase/migrations/20260927000002_content_translations_batch1.sql
from content/translations/*.json (reviewed RU/EN translations).

Kyrgyz stays canonical in the content rows; this only writes
public.content_translations. Re-run after editing the JSON files."""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
T = ROOT / 'content' / 'translations'
OUT = ROOT / 'supabase' / 'migrations' / '20260927000002_content_translations_batch1.sql'


def q(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    rows = []
    for lang in ('ru', 'en'):
        data = json.loads((T / f'culture_batch1.{lang}.json').read_text(encoding='utf-8'))
        for content_id, fields in data.items():
            for field, value in fields.items():
                rows.append(('culture_item', content_id, lang, field, value))
    facts = json.loads((T / 'explore_facts_batch1.json').read_text(encoding='utf-8'))
    for region_id, by_lang in facts.items():
        if region_id.startswith('_'):
            continue
        for lang in ('ru', 'en'):
            for index, value in enumerate(by_lang[lang]):
                rows.append(('explore_region', region_id, lang, f'fact.{index}', value))
    lines = [
        '-- Translation batch 1 (reviewed RU/EN) - generated by scripts/build-content-translations.py',
        '-- from content/translations/*.json; Kyrgyz source rows are not modified.',
        '-- Culture: the 20 items linked from Collections, Trails and Challenges.',
        '-- Explore: facts of the 6 destinations with no claim awaiting verification.',
        'insert into public.content_translations (content_type, content_id, language, field, value, status) values',
        ',\n'.join(f"  ({q(a)}, {q(b)}, {q(c)}, {q(d)}, {q(e)}, 'reviewed')" for a, b, c, d, e in rows),
        'on conflict (content_type, content_id, language, field) do update set value = excluded.value, status = excluded.status, updated_at = now();',
    ]
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{len(rows)} rows -> {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
